<script type="text/javascript" src="HotelReservationForm.AJAX/Tabstrip.XML/Scripts/TabStrip.XML.js"></script>
<script type="text/javascript" src="HotelReservationForm.AJAX/Forms.JS/Scripts/Forms.JS.js"></script>
<script type="text/javascript" src="HotelReservationForm.AJAX/HotelReservationForm.AJAX/Scripts/HotelReservationForm.AJAX.js"></script>
<script type="text/javascript" src="HotelReservationForm.AJAX/jQuery.HotelReservationForm.AJAX/Scripts/jquery-1.3.2.min.js"></script>
<style type="text/css">
#ajaxhotelform
{
	visibility: hidden;
}
</style>