<div class="demoHeader">
			<h1><a href="index.php" title="TabStrip.XML Demo Home Page">TabStrip.XML</a></h1>
			<div>
				<ul>
					<li><a href="http://acidjs.wemakesites.net/tabstrip-xml.html" target="_blank" title="TabStrip.XML Online">TabStrip.XML Online</a></li>
					<li><a href="http://acidmartin.wemakesites.net/DownloadAdmin/click.php?id=87" title="Download">Download</a></li>
					<li><a href="http://acidjs.wemakesites.net/buy-software.html" title="Purchase Full Version" target="_blank">Purchase Full Version</a></li>
					<li><a href="http://acidjs.wemakesites.net/" title="Acid.JS Web 2.0 Component Libary" target="_blank">Acid.JS Web 2.0 Component Libary</a></li>
				</ul>
			</div>
		</div>
		