<h3>More Methods</h3>
<label for="MethodsSelector">Jump to method: </label><select id="MethodsSelector">
	<option value="0">Programmatically add tabs to a tabstrip</option>
	<option value="1">Programmatically remove tabs from a tabstrip</option>
	<option value="2">Programmatically set new skin to a tabstrip</option>
	<option value="3">Programmatically remove a tabstrip from the DOM of the page</option>
	<option value="4">Create a tabstrip in runtime</option>
	<option value="5">Remove all tabs</option>
	<option value="6">Hide tab</option>
	<option value="7">Show tab</option>
	<option value="8">Disable tab</option>
	<option value="9">Enable tab</option>
	<option value="10">Programmatically select tab</option>
</select>